version: '2'

services:
  apache:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
      - "8443:443"
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_USER: owncloud
      MYSQL_PASSWORD: owncloud
      MYSQL_DATABASE: owncloud
      MYSQL_ROOT_PASSWORD: owncloud
    command: [ "--default-authentication-plugin=mysql_native_password" ]
